### ISSUE TITLE
FRONT-END TODO(S) LIST

### ISSUE THREAD

**Issue by Namchee** [ftis-admin/pinjam-ruang#6]
### This list is sorted on descending order by it's importance level

- [ ] Implement API - *still waiting atm...*
- [ ] Do ACTUAL routing - _currently impossible due to the unavailability of the API_
- [x] Implement state-management system
- [x] Overhaul Settings.vue (mostly done, create another issue if you see some ~~funny~~ stuffs)
- [x] Do basic wireframe - _mostly done, leave a comment if you want to do further enhancement(s)_
